version: '3.1'

volumes:
  pgadmin_data: {}

services:
  account-service-first:
    image: account-service-first
    env_file: .env
    container_name: account-service-first
    build:
      dockerfile: Dockerfile.accountService
      context: ./
    ports:
      - "8001:8081"

  account-service-second:
      image: account-service-second
      env_file: .env2
      container_name: account-service-second
      build:
        dockerfile: Dockerfile.accountService
        context: ./
      ports:
        - "8002:8081"

  operations-service-first:
    container_name: operations-service-first
    image: operations-service-first
    env_file: .env
    ports:
      - "8003:8081"
    build:
      context: ./
      dockerfile: Dockerfile.operationService

  fees-service-first:
      container_name: fees-service-first
      image: fees-service-first
      env_file: .env
      ports:
        - "8004:8081"
      build:
        context: ./
        dockerfile: Dockerfile.feesService

  cashbacks-service-first:
      container_name: cashbacks-service-first
      image: cashbacks-service-first
      env_file: .env
      ports:
        - "8005:8081"
      build:
        context: ./
        dockerfile: Dockerfile.cashbackService

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -Xms128m -Xmx256m
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_HOSTNAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

