//Создание 1 аккаунта
curl --header "Content-Type: application/json" \
--request POST \
--data '{
          "initialAmount": 100,
          "category": "first"
        }' \
http://localhost:8010/account HTTP/1.1

//Создание 2 аккаунта
curl --header "Content-Type: application/json" \
--request POST \
--data '{
          "initialAmount": 2000,
          "category": "second"
        }' \
http://localhost:8003/account HTTP/1.1

//Перевод денег с 1 на 2 аккаунт
curl --header "Content-Type: application/json" \
--request POST \
--data '{
          "sourceId": 1,
          "destinationId": 2,
          "value": 5000
        }' \
http://localhost:8003/transfer HTTP/1.1




